"use strict";
var path = require("path");
var util = require("util");
var yeoman = require("yeoman-generator");

module.exports = ExpressGenerator;

function ExpressGenerator() {
	yeoman.generators.Base.apply(this, arguments);
}

util.inherits(ExpressGenerator, yeoman.generators.Base);

ExpressGenerator.prototype.welcome = function welcome() {
	var logo = "        " +
			"     EXPRESS" +
			"THE CUSTOM" +
			"               YEOMAN GENERATOR",
		welcomeText = "Welcome to the Express custom generator";
		this.log.writeln(logo + "\n" + welcomeText);
}

ExpressGenerator.prototype.promptUser = function promptUser() {

	var boolRegex = /^(?:y(?:es)?|n(?:o)?)$/i,
		boolFilter = function (value) {
			value = value.toLowerCase();
			if (value === "y" || value === "yes") {
				return true;
			}
			return false;
		};
	var cb = this.async(),
		self = this;
	var prompts = [
		{
			name: "name",
			message: "What is the name of your project?",
			required: true,
			advanced: false
		},

		{
			name: "description",
			message: "Give me a description on what your app is supposed to do",
			default: "App generated by express custom generator",
			required: false,
			advanced: false
		},

		{
			name: "keywords",
			message: "Give me keywords that correspond to the site. (comma-separated)",
			default: "",
			required: false,
			advanced: true
		},

		{
			name: "icons",
			type: "confirm",
			message: "Would you like to enable and include default icomoon icons?",
			required: true,
			advanced: false,
			pattern: boolRegex
		},

		//js libraries to include
		{
			name: "modernizr",
			type: "confirm",
			message: "Would you like to use Modernizr?",
			required: true,
			advanced: false,
			pattern: boolRegex
		},

		{
			name: "jQuery",
			message: "Would you like to use jQuery?",
			type: "confirm",
			required: true,
			advanced: false,
			pattern: boolRegex
		},

		{
			name: "requirejs",
			message: "Would you like to use requireJS and AMD modules?",
			type: "confirm",
			required: true,
			advanced: false,
			pattern: boolRegex
		},

		//author and header info
		{
			name: "authorName",
			message: "Who is the creator of this site?",
			default: "Sean Goresht",
			required: false,
			advanced: true
		},

		{
			name: "authorURL",
			message: "What is the site where the author can be reached?",
			default: "http://seangoresht.com",
			required: true,
			advanced: true
		},

		{
			name: "authorGitHub",
			default: "srsgores",
			message: "What is your gitHub account?",
			required: true,
			advanced: true
		},

		{
			name: "authorTwitter",
			default: "srsgores",
			message: "What is your Twitter account?",
			required: true,
			advanced: true
		},

		{
			name: "pages",
			message: "(Optional) Enter the pages you wish to create for this site -- comma-separated",
			default: "about, features, contact",
			required: false,
			advanced: true
		},

		{
			name: "lessMiddleWare",
			type: "confirm",
			message: "(Optional) Would you like to use LESS?",
			default: false,
			required: false,
			advanced: true
		}
	];

	this.prompt(prompts, function (props) {
		// set the property to parse the gruntfile
		self.name = props.name;
		self.description = props.description;
		self.keywords = props.keywords;
		self.icons = props.icons;
		self.modernizr = props.modernizr;
		self.jQuery = props.jQuery;
		self.requirejs = props.requirejs;
		self.authorName = props.authorName;
		self.authorURL = props.authorURL;
		self.authorGitHub = props.authorGitHub;
		self.authorTwitter = props.authorTwitter;
		self.authorPages = props.authorPages;
		self.lessMiddleWare = props.lessMiddleWare;

		//once the prompts are finished, do the callback
		cb();
	}.bind(this));
};

ExpressGenerator.prototype.setupEnv = function setupEnv() {
	this.sourceRoot(path.join(__dirname, "../templates/custom"));
	this.directory(".", ".", true);
	this.mkdir("public/img");
	this.mkdir("public/js/components");
	this.mkdir("public/js");
};

ExpressGenerator.prototype.packageJSON = function packageJSON() {
	this.template("_package.json", "package.json");
	this.template("_bower.json", "bower.json");
};

ExpressGenerator.prototype.generateContent = function generateContent() {
	//scaffold main application fild
	this.template("_app.js", "app.js");
	//scaffold main layout file
	this.template("views/_layout.jade", "views/layout.jade");
	//scaffold main route file with user's info
	this.template("routes/_index.js", "routes/index.js");
};

ExpressGenerator.prototype.includeIcomoon = function includeIcomoon() {
	if (this.icomoon === true) {
		this.copy("public/sass/partials/icomoon/_icomoon.scss", "public/sass/partials/icomoon/_icomoon.scss");
		this.copy("public/sass/partials/icomoon/_icomoon_session.json", "public/fonts/icomoon/session/icomoon_session.json");
		this.copy("public/fonts/icomoon/icomoon.eot", "public/fonts/icomoon/icomoon.eot");
		this.copy("public/fonts/icomoon/icomoon.svg", "public/fonts/icomoon/icomoon.svg");
		this.copy("public/fonts/icomoon/icomoon.ttf", "public/fonts/icomoon/icomoon.woff");
	}
};

ExpressGenerator.prototype.generateRequire = function generateRequire() {
	if (this.requirejs === true) {
		this.mkdir("public/js/app");
		this.mkdir("public/js/lib");
		this.template("public/js/_app.js", "public/js/app/app.js");
	}
	this.template("public/js/_main.js", "public/js/main.js");
}