// Boolean answer regexp
var boolRegex = /^(?:y(?:es)?|n(?:o)?)$/i,
	boolFilter = function (value) {
		value = value.toLowerCase();
		if (value === "y" || value === "yes") {
			return true;
		}
		return false;
	};

//include prompts here
module.exports = {
	name: {
		name: "name",
		description: "What is the name of your project?",
		required: true,
		advanced: false
	},

	description: {
		name: "description",
		description: "Give me a description on what your app is supposed to do",
		default: "App generated by express custom generator",
		required: false,
		advanced: false
	},

	keywords: {
		name: "keywords",
		description: "Give me keywords that correspond to the site. (comma-separated)",
		default: "",
		required: false,
		advanced: true
	},

	icons: {
		name: "icons",
		description: "Would you like to enable and include default icomoon icons?",
		required: true,
		advanced: false,
		pattern: boolRegex
	},

	//js libraries to include
	modernizr: {
		name: "modernizr",
		description: "Would you like to use Modernizr?",
		required: true,
		advanced: false,
		pattern: boolRegex
	},

	jQuery: {
		name: "jQuery",
		description: "Would you like to use jQuery?",
		required: true,
		advanced: false,
		pattern: boolRegex
	},

	requirejs: {
		name: "requirejs",
		description: "Would you like to use requireJS and AMD modules?",
		required: true,
		advanced: false,
		pattern: boolRegex
	},

	//author and header info
	authorName: {
		name: "authorName",
		description: "Who is the creator of this site?",
		default: user.name,
		required: false,
		advanced: true
	},

	authorURL: {
		name: "authorURL",
		description: "What is the site where the author can be reached?",
		required: true,
		advanced: true
	},

	authorGitHub: {
		name: "authorGitHub",
		description: "What is your gitHub account?",
		required: true,
		advanced: true
	},

	authorTwitter: {
		name: "authorTwitter",
		description: "What is your Twitter account?",
		required: true,
		advanced: true
	},

	pages: {
		name: "pages",
		description: "(Optional) Enter the pages you wish to create for this site -- comma-separated",
		default: "about, features, contact",
		required: false,
		advanced: true
	}
};